name = "scada-relay"
main = "worker.js"
compatibility_date = "2026-02-27"

[vars]
SUPABASE_URL = "https://xqkbrlcdbgykmatzwvct.supabase.co"
SUPABASE_TABLE = "scada_reports"
AUTH_TABLE = "scada_auth"
AUTH_ROW_ID = "1"
AZURE_DOCINTEL_MODEL_ID = "prebuilt-layout"
AZURE_DOCINTEL_API_VERSION = "2024-11-30"
AZURE_DOCINTEL_FEATURES = "ocrHighResolution"
AZURE_DOCINTEL_OUTPUT_CONTENT_FORMAT = "text"
